### PR TITLE
Improve "Development and release" section in README

### LINKED ISSUE #19: Improve "Development and release" section in README
* Update changelog before rubygems.org release
* Example commands

### PR DESCRIPTION
**Pull request by roback**
Do we have to update the [releases page](https://github.com/twingly/twingly-analytics-api-ruby/releases) manually? If yes, that step should be added.

close #19

### CODE REVIEW

**Comment by jage** [comment]
@roback https://github.com/lostisland/faraday/commit/f78d51da17b5af4ff8460d142f843e31aa0875c0 in https://github.com/lostisland/faraday/releases/tag/v0.9.2 broke the specs since VCR matches on method and URI.

I'll record new cassettes and ensure we have at least Faraday 0.9.2.

**Comment by roback** [comment]
Aha, thanks :)

**Comment by jage** [comment]
> Do we have to update the releases page manually? If yes, that step should be added.

Yes!

**Comment by walro** [comment]
LGTM! I think it's easiest to try to follow the instructions the next time we release and make any final touchups then.

**Comment by roback** [comment]
> LGTM! I think it's easiest to try to follow the instructions the next time we release and make any final touchups then.

Yes, sounds good :)

**Pull request merged**
